### ISSUE TITLE
Error while returning JSON when the top level element is an array

### ISSUE THREAD

**Issue by phungthomas** [csia-pme/csia-pme#16]
When the result of a microservice has an array as top level element as JSON, the engine will throw an error.

Example of microservice result:
```json
[
  {
    "level": 1,
    "blockNum": 1
  }
]
```

Engine error:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
[...]
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/api/api.py", line 236, in processCallback
    data.update(requestData)
ValueError: dictionary update sequence element #0 has length 9; 2 is required
```

**Comment by PxReaz** [comment]
Fixed with engine refactor #35
